spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.bgincodjshyqtvecamzz
    password: Ineedf126soi
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect